import type { Metadata } from "next";
import { ThemeProvider } from "@/contexts/theme-context";
import Container from "@/components/boundtree/Container";
import BoundTreeHeader from "@/components/boundtree/BoundTreeHeader";

export const metadata: Metadata = {
  title: "Bound Tree by Next",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <BoundTreeHeader />
      <Container>
        <ThemeProvider>{children}</ThemeProvider>
      </Container>
    </>
  );
}
